language: python
dist: trusty

python:
  - "2.7"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - mysql

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - nvm install v7.10.0
  - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
  - sudo python install.py --develop --user travis --without-bench-setup
  - sudo pip install -e ~/bench

  # - cd ~/
  # - wget https://saucelabs.com/downloads/sc-4.4.7-linux.tar.gz
  # - tar -xf sc-4.4.7-linux.tar.gz
  # - mv sc-4.4.7-linux sc-binary
  # - ~/sc-binary/bin/sc -u netchampfaris -k 90fad2ae-008e-43d9-a0fc-d592cb5fe141 &
  # - sleep 20

  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - cd ~/ && bench init frappe-bench --frappe-path $TRAVIS_BUILD_DIR
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/

before_script:
  - mysql -u root -ptravis -e 'create database test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis
  
  - cd ~/frappe-bench
  - npm install babel-core less chokidar babel-preset-es2015 babel-preset-es2016 babel-preset-es2017 babel-preset-babili chromedriver
  - npm install -g nightwatch
  # - node apps/frappe/frappe/nightwatch.js
  - bench use test_site
  - bench reinstall --yes
  - bench start &
  - sleep 10

script:
  # - set -e
  # - bench --verbose run-tests
  # - chromedriver --port=9515 &
  # - while ! curl localhost:9515; do echo -n .; sleep 1; done
  - nightwatch --config apps/frappe/frappe/nightwatch.js --env local --app frappe
